SASS-2042: Employment Summary Iteration
hmrc/income-tax-submission-performance-tests pull request #53
Opened 2022-01-21 12:00 UTC by joeyymoore

### Description

- Employment Summary Iteration

https://jira.tools.tax.service.gov.uk/browse/SASS-2042

### Checklist PR Reviewer
##### Before Reviewing
 - [ ]  Have you pulled the branch down?
 - [ ]  Have you assigned yourself to the PR? 
 - [ ]  Have you moved the task to “in review” on JIRA? 
 - [ ]  Have you checked to ensure all dependencies are up to date? 
 - [ ] Have you checked to ensure its been rebased against the current version of master?

##### Whilst Reviewing
 - [ ]  Have you run the tests?
 - [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ] Have you checked for merge conflicts or any changes in the current master that may affect the current pull request? i.e. does it need another rebase?
 - [ ]  Have you checked to make sure there are no builds in the pipeline before you merge? 
 - [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR 
 - [ ]  Have you run the tests?
 - [ ]  Have you addressed warnings where appropriate? 
 - [ ] Have you rebased against the current version of master?

2022-01-24 10:22 UTC, joeyymoore commented
Need to be merged with https://github.com/hmrc/income-tax-employment-frontend/pull/268 and https://github.com/hmrc/income-tax-submission-journey-tests/pull/121

2022-01-25 15:54 UTC, ina-tu requested changes

2022-01-25 15:54 UTC, ina-tu commented on src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
> +    getEmploymentAddNewUserUrl(taxYearEOY)
I'm not sure if this line is needed

2022-01-25 15:54 UTC, ina-tu commented on src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
> +    getEmploymentAddNewUserUrl(taxYearEOY)
same here

2022-01-25 16:41 UTC, joeyymoore commented on src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
> +    getEmploymentAddNewUserUrl(taxYearEOY)
Same as above

2022-01-26 09:43 UTC, ina-tu approved these changes

2022-01-27 14:55 UTC, ina-tu approved these changes

2022-01-27 14:58 UTC, merged